"""Orchestration state models for Texere workflows."""

import operator
from typing import Annotated, Any, Optional

from langchain_core.messages import BaseMessage
from typing_extensions import TypedDict


class WorkflowState(TypedDict, total=False):
    """
    Core workflow state representing the complete context for a Texere orchestration.

    This TypedDict defines the shared state structure for LangGraph workflows,
    with reducer semantics for append-only fields.

    Slice 1 includes only essential fields for minimal graph foundation:
    - user_request: Original user query/request
    - messages: Conversation history (with add reducer)
    - plan: Structured plan/reasoning (replace-only)
    """

    # User input and context
    user_request: str
    """Original user query/request for the workflow."""

    # Execution context
    thread_id: str
    """Long-lived session identifier, used for checkpointing and resumption."""

    run_id: str
    """Individual workflow execution identifier."""

    # Messages (short-term memory)
    messages: Annotated[list[BaseMessage], operator.add]
    """Conversation history, deduplicated and windowed. Uses add reducer."""

    # Planning and decomposition
    plan: Optional[str]
    """Structured plan/reasoning generated by LLM."""

    subtasks: Annotated[list[str], operator.add]
    """Decomposed tasks from planning. Uses add reducer."""

    # Code understanding (RAG-backed)
    codebase_summary: Optional[str]
    """High-level codebase overview."""

    relevant_files: Annotated[list[str], operator.add]
    """Retrieved code snippets. Uses add reducer."""

    # Tool execution tracking
    tool_calls: Annotated[list[dict], operator.add]
    """Record of all tool invocations. Uses add reducer."""

    tool_results: dict[str, Any]
    """Latest results from tools (replace-only)."""

    # Implementation state
    proposed_changes: Optional[str]
    """Staged implementation plan."""

    executed_changes: Annotated[list[dict], operator.add]
    """Applied changes. Uses add reducer."""

    # Testing and validation
    test_results: Optional[dict]
    """Test execution results."""

    validation_errors: Annotated[list[str], operator.add]
    """Accumulated validation errors. Uses add reducer."""

    # Final output
    final_response: Optional[str]
    """Final result for user."""

    success: bool
    """Workflow completion status."""

    error_context: Optional[str]
    """Error details if failed."""
